version: v0.1
displayName: Store App Load Test
description: Locust load test
testPlan: locustfile.py
testType: Locust
engineInstances: 1
env:
  - name: LOCUST_USERS
    value: '50'
  - name: LOCUST_RUN_TIME
    value: '120'
  - name: LOCUST_SPAWN_RATE
    value: '1'
resourceId: >-
  /subscriptions/7c71b563-0dc0-4bc0-bcf6-06f8f0516c7a/resourceGroups/krinar-canary/providers/Microsoft.LoadTestService/loadtests/Canary_sanity
secrets:
  - name: HOST
    value: ''
    type: SECRET_VALUE
  - name: DEBUG_MODE
    value: ''
    type: SECRET_VALUE
configurationFiles:
  - requirements.txt
testId: 49e317ae-75c0-4823-8b1d-66ab779eadf0
